dist: trusty
language: scala
jdk: openjdk11
scala:
  - 2.13.1

stages:
  - test
  - name: release
    if: tag =~ ^v

jobs:
  include:
    - stage: test
      before_script:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
        - export PATH=$PWD/geckodriver:$PATH
      script:
        - sbt +test +publishLocal
        - cd example && sbt compileStatics
    - stage: release
      script:
        - openssl aes-256-cbc -K $encrypted_f00a6d0a0202_key -iv $encrypted_f00a6d0a0202_iv -in travis/travis.gpg.enc -out travis/travis.gpg -d
        - gpg --import travis/travis.gpg
        - test $TRAVIS_PULL_REQUEST = "false" && sbt +publishSigned sonatypeBundleRelease

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.m2
    - $HOME/.cache
    - $HOME/.sbt